SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE IF EXISTS MOBYDIC_FAQ;
DROP TABLE IF EXISTS MOBYDIC_NOTICE;
DROP TABLE IF EXISTS MOBYDIC_QNA_REPLY;
DROP TABLE IF EXISTS MOBYDIC_QNA;
DROP TABLE IF EXISTS MOBYDIC_RESERVATION_REPLY;
DROP TABLE IF EXISTS MOBYDIC_RESERVATION;




/* Create Tables */

CREATE TABLE MOBYDIC_FAQ
(
	FAQ_NUMBER int NOT NULL AUTO_INCREMENT,
	QUESTION varchar(255) NOT NULL,
	ANSWER varchar(255) NOT NULL,
	PRIORITY int,
	CREATE_DATE datetime NOT NULL,
	UPDATE_DATE datetime NOT NULL,
	PRIMARY KEY (FAQ_NUMBER),
	UNIQUE (FAQ_NUMBER)
);


CREATE TABLE MOBYDIC_NOTICE
(
	NOTICE_NUMBER int NOT NULL AUTO_INCREMENT,
	SUBJECT varchar(255) NOT NULL,
	CONTENT varchar(255) NOT NULL,
	CREATE_DATE datetime NOT NULL,
	UPDATE_DATE datetime NOT NULL,
	PRIMARY KEY (NOTICE_NUMBER),
	UNIQUE (NOTICE_NUMBER)
);


CREATE TABLE MOBYDIC_QNA
(
	QNA_NUMBER int NOT NULL AUTO_INCREMENT,
	MEMBER_NAME varchar(50) NOT NULL,
	MEMBER_PHONE varchar(50) NOT NULL,
	MEMBER_EMAIL varchar(200) NOT NULL,
	PASSWORD varchar(255) NOT NULL,
	SUBJECT varchar(150) NOT NULL,
	CONTENT varchar(255) NOT NULL,
	CREATE_DATE datetime NOT NULL,
	UPDATE_DATE datetime NOT NULL,
	PRIMARY KEY (QNA_NUMBER)
);


CREATE TABLE MOBYDIC_QNA_REPLY
(
	QNA_REPLY_NUMBER int NOT NULL AUTO_INCREMENT,
	QNA_NUMBER int NOT NULL,
	MEMBER_NAME varchar(50) NOT NULL,
	CONTENT varchar(255) NOT NULL,
	CREATE_DATE datetime NOT NULL,
	UPDATE_DATE datetime NOT NULL,
	PRIMARY KEY (QNA_REPLY_NUMBER, QNA_NUMBER)
);


CREATE TABLE MOBYDIC_RESERVATION
(
	RESERVATION_NUMBER int NOT NULL AUTO_INCREMENT,
	VISIT_DATE date NOT NULL,
	VISIT_TIME varchar(10) NOT NULL,
	MEMBER_NAME varchar(50) NOT NULL,
	MEMBER_PHONE varchar(50) NOT NULL,
	MEMBER_EMAIL varchar(200) NOT NULL,
	PASSWORD varchar(255) NOT NULL,
	PICK_YN char(1) NOT NULL,
	PACKAGE_CODE tinyint NOT NULL,
	PAY_STATUS_CODE tinyint NOT NULL,
	DESCRIPTION varchar(255),
	PERSONNEL tinyint NOT NULL,
	CREATE_DATE datetime NOT NULL,
	UPDATE_DATE datetime NOT NULL,
	PRIMARY KEY (RESERVATION_NUMBER, VISIT_DATE)
);


CREATE TABLE MOBYDIC_RESERVATION_REPLY
(
	RESERVATION_REPLY_NUMBER int NOT NULL AUTO_INCREMENT,
	RESERVATION_NUMBER int NOT NULL,
	VISIT_DATE date NOT NULL,
	MEMBER_NAME varchar(50) NOT NULL,
	CONTENT varchar(255) NOT NULL,
	CREATE_DATE datetime NOT NULL,
	UPDATE_DATE datetime NOT NULL,
	PRIMARY KEY (RESERVATION_REPLY_NUMBER, RESERVATION_NUMBER),
	UNIQUE (RESERVATION_REPLY_NUMBER)
);



/* Create Foreign Keys */

ALTER TABLE MOBYDIC_QNA_REPLY
	ADD FOREIGN KEY (QNA_NUMBER)
	REFERENCES MOBYDIC_QNA (QNA_NUMBER)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE MOBYDIC_RESERVATION_REPLY
	ADD FOREIGN KEY (RESERVATION_NUMBER, VISIT_DATE)
	REFERENCES MOBYDIC_RESERVATION (RESERVATION_NUMBER, VISIT_DATE)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



