SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE IF EXISTS MOBYDIC_NOTICE;
DROP TABLE IF EXISTS MOBYDIC_QNA_REPLY;
DROP TABLE IF EXISTS MOBYDIC_QNA;
DROP TABLE IF EXISTS MOBYDIC_RESERVATION;




/* Create Tables */

CREATE TABLE MOBYDIC_NOTICE
(
	NOTICE_NUMBER int NOT NULL,
	SUBJECT varchar(150) NOT NULL,
	CONTENT blob NOT NULL,
	CREATE_DATE datetime NOT NULL,
	UPDATE_DATE datetime NOT NULL,
	PRIMARY KEY (NOTICE_NUMBER)
);


CREATE TABLE MOBYDIC_QNA
(
	QNA_NUMBER int NOT NULL AUTO_INCREMENT,
	MEMBER_NAME varchar(50) NOT NULL,
	MEMBER_PHONE varchar(50) NOT NULL,
	MEMBER_EMAIL varchar(100) NOT NULL,
	PASSWORD varchar(255) NOT NULL,
	SUBJECT varchar(150) NOT NULL,
	CONTENT blob NOT NULL,
	CREATE_DATE datetime NOT NULL,
	UPDATE_DATE datetime NOT NULL,
	PRIMARY KEY (QNA_NUMBER)
);


CREATE TABLE MOBYDIC_QNA_REPLY
(
	QNA_REPLY_NUMBER int NOT NULL AUTO_INCREMENT,
	QNA_NUMBER int NOT NULL,
	MEMBER_NAME varchar(50) NOT NULL,
	CONTENT varchar(255) NOT NULL,
	CREATE_DATE datetime NOT NULL,
	UPDATE_DATE datetime NOT NULL,
	PRIMARY KEY (QNA_REPLY_NUMBER, QNA_NUMBER)
);


CREATE TABLE MOBYDIC_RESERVATION
(
	RESERVATION_NUMBER int NOT NULL AUTO_INCREMENT,
	RESERVATION_DATE date NOT NULL,
	RESERVATION_CODE tinyint NOT NULL,
	MEMBER_NAME varchar(50) NOT NULL,
	MEMBER_PHONE varchar(50) NOT NULL,
	MEMBER_EMAIL ,
	PASSWORD varchar(255) NOT NULL,
	PICKUP_YN char(1) NOT NULL,
	DESCRIPTION varchar(255),
	PERSONNEL_1 tinyint NOT NULL,
	PERSONNEL_2 tinyint DEFAULT 0 NOT NULL,
	CREATE_DATE datetime NOT NULL,
	UPDATE_DATE datetime NOT NULL,
	PRIMARY KEY (RESERVATION_NUMBER, RESERVATION_DATE)
);



/* Create Foreign Keys */

ALTER TABLE MOBYDIC_QNA_REPLY
	ADD FOREIGN KEY (QNA_NUMBER)
	REFERENCES MOBYDIC_QNA (QNA_NUMBER)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



